name: Build and upload to PyPI

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - run: python -m pip install cibuildwheel==2.11.1
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD_LINUX: apt-get update && apt-get install -y libeigen3-dev libxml2-dev
          CIBW_BUILD: cp3*-*
          CIBW_SKIP: cp27-* cp35-* *-win32 *-manylinux_i686 *musllinux*
          CIBW_BUILD_VERBOSITY: 1
          CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux2014"
          CIBW_TEST_COMMAND: "python tests/test_import.py"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
